In [1]:
import numpy as np 
import pandas as pd 
import seaborn as sns 
import matplotlib.pyplot as plt

In [3]:
data = pd.read_csv('matches.csv')

In [4]:
data.shape

(104, 42)

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 104 entries, 0 to 103
Data columns (total 42 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   round               104 non-null    object
 1   gameweek            72 non-null     float64
 2   dayofweek           104 non-null    object
 3   date                104 non-null    object
 4   start_time          104 non-null    object
 5   home_team           104 non-null    object
 6   away_team           104 non-null    object
 7   score               104 non-null    object
 8   home_score          100 non-null    float64
 9   away_score          100 non-null    float64
 10  attendance          104 non-null    object
 11  venue               104 non-null    object
 12  referee             104 non-null    object
 13  home_formation      104 non-null    object
 14  away_formation      104 non-null    object
 15  home_manager        104 non-null    object
 16  away_manager        104 non-null    object
 17  home_captain        104 non-null    object
 18  away_captain        104 non-null    object
 19  home_possession     104 non-null    int64
 20  away_possession     104 non-null    int64
 21  home_sot            104 non-null    int64
 22  away_sot            104 non-null    int64
 23  home_total_shots    104 non-null    int64
 24  away_total_shots    104 non-null    int64
 25  home_saves          104 non-null    int64
 26  away_saves          104 non-null    int64
 27  home_cards_yellow   104 non-null    int64
 28  away_cards_yellow   104 non-null    int64
 29  home_cards_red      104 non-null    int64
 30  away_cards_red      104 non-null    int64
 31  home_fouls          104 non-null    int64
 32  away_fouls          104 non-null    int64
 33  home_corners        104 non-null    int64
 34  away_corners        104 non-null    int64
 35  home_crosses        104 non-null    int64
 36  away_crosses        104 non-null    int64
 37  home_interceptions  104 non-null    int64
 38  away_interceptions  104 non-null    int64
 39  home_offsides       99 non-null     float64
 40  away_offsides       99 non-null     float64
 41  notes               9 non-null      object
dtypes: float64(5), int64(20), object(17)
memory usage: 34.3+ KB

In [6]:
data.describe()

,gameweek,home_score,away_score,home_possession,away_possession,home_sot,away_sot,home_total_shots,away_total_shots,home_saves,...,home_fouls,away_fouls,home_corners,away_corners,home_crosses,away_crosses,home_interceptions,away_interceptions,home_offsides,away_offsides
count,72.000000,100.000000,100.00000,104.000000,104.000000,104.000000,104.000000,104.000000,104.000000,104.000000,...,104.000000,104.000000,104.000000,104.000000,104.000000,104.000000,104.000000,104.000000,99.000000,99.000000
mean,2.000000,1.760000,1.26000,52.423077,47.701923,4.846154,3.673077,14.019231,10.769231,2.403846,...,11.625000,11.567308,5.182692,3.961538,17.817308,14.201923,8.086538,8.634615,1.919192,1.797980
std,0.822226,1.518372,1.25223,13.101317,13.093302,3.108926,2.502202,6.422020,5.846301,1.913261,...,4.027063,4.403803,3.409764,2.661933,10.338696,7.325153,3.859450,3.128503,1.523133,1.597062
min,1.000000,0.000000,0.00000,24.000000,21.000000,0.000000,0.000000,2.000000,2.000000,0.000000,...,3.000000,1.000000,0.000000,0.000000,4.000000,1.000000,1.000000,3.000000,0.000000,0.000000
25%,1.000000,1.000000,0.00000,43.000000,38.000000,2.000000,2.000000,8.750000,7.000000,1.000000,...,9.000000,8.000000,3.000000,2.000000,11.750000,9.000000,5.000000,6.000000,1.000000,1.000000
50%,2.000000,1.000000,1.00000,52.500000,47.500000,4.000000,3.000000,13.000000,10.000000,2.000000,...,11.000000,12.000000,4.000000,4.000000,15.000000,13.000000,7.500000,8.500000,2.000000,1.000000
75%,3.000000,3.000000,2.00000,62.000000,57.000000,7.000000,5.000000,19.000000,14.000000,3.000000,...,13.250000,14.000000,7.000000,5.000000,22.000000,18.000000,10.000000,11.000000,3.000000,3.000000
max,3.000000,7.000000,6.00000,79.000000,76.000000,15.000000,11.000000,32.000000,35.000000,9.000000,...,24.000000,25.000000,19.000000,14.000000,56.000000,47.000000,21.000000,16.000000,8.000000,6.000000

In [13]:
data.head(105)

,round,gameweek,dayofweek,date,start_time,home_team,away_team,score,home_score,away_score,...,away_fouls,home_corners,away_corners,home_crosses,away_crosses,home_interceptions,away_interceptions,home_offsides,away_offsides,notes
0,Group stage,1.0,Thu,2026-06-11,13:00,Mexico,South Africa,2–0,2.0,0.0,...,11,3,1,12,8,8,7,1.0,1.0,NaN
1,Group stage,1.0,Thu,2026-06-11,20:00,Korea Republic,Czechia,2–1,2.0,1.0,...,16,4,5,12,15,11,7,2.0,2.0,NaN
2,Group stage,1.0,Fri,2026-06-12,15:00,Canada,Bosnia–Herz,1–1,1.0,1.0,...,20,9,4,24,10,4,10,1.0,0.0,NaN
3,Group stage,1.0,Fri,2026-06-12,18:00,United States,Paraguay,4–1,4.0,1.0,...,17,3,1,17,5,11,9,2.0,1.0,NaN
4,Group stage,1.0,Sat,2026-06-13,12:00,Qatar,Switzerland,1–1,1.0,1.0,...,11,3,10,8,35,10,7,0.0,1.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99,Quarter-finals,NaN,Sat,2026-07-11,20:00,Argentina,Switzerland,3–1,3.0,1.0,...,18,8,2,22,19,12,6,4.0,3.0,Required Extra Time
100,Semi-finals,NaN,Tue,2026-07-14,14:00,France,Spain,0–2,0.0,2.0,...,12,7,1,20,8,8,7,4.0,5.0,NaN
101,Semi-finals,NaN,Wed,2026-07-15,15:00,England,Argentina,1–2,1.0,2.0,...,15,1,6,15,19,9,6,1.0,3.0,NaN
102,Third-place match,NaN,Sat,2026-07-18,17:00,France,England,4–6,4.0,6.0,...,8,3,4,6,12,8,11,3.0,3.0,NaN
103,Final,NaN,Sun,2026-07-19,15:00,Spain,Argentina,1–0,1.0,0.0,...,25,9,4,27,8,11,16,4.0,1.0,Required Extra Time

In [11]:
data.isnull().sum()

round                  0
gameweek              32
dayofweek              0
date                   0
start_time             0
home_team              0
away_team              0
score                  0
home_score             4
away_score             4
attendance             0
venue                  0
referee                0
home_formation         0
away_formation         0
home_manager           0
away_manager           0
home_captain           0
away_captain           0
home_possession        0
away_possession        0
home_sot               0
away_sot               0
home_total_shots       0
away_total_shots       0
home_saves             0
away_saves             0
home_cards_yellow      0
away_cards_yellow      0
home_cards_red         0
away_cards_red         0
home_fouls             0
away_fouls             0
home_corners           0
away_corners           0
home_crosses           0
away_crosses           0
home_interceptions     0
away_interceptions     0
home_offsides          5
away_offsides          5
notes                 95
dtype: int64

In [14]:
data.columns

Index(['round', 'gameweek', 'dayofweek', 'date', 'start_time', 'home_team',
       'away_team', 'score', 'home_score', 'away_score', 'attendance', 'venue',
       'referee', 'home_formation', 'away_formation', 'home_manager',
       'away_manager', 'home_captain', 'away_captain', 'home_possession',
       'away_possession', 'home_sot', 'away_sot', 'home_total_shots',
       'away_total_shots', 'home_saves', 'away_saves', 'home_cards_yellow',
       'away_cards_yellow', 'home_cards_red', 'away_cards_red', 'home_fouls',
       'away_fouls', 'home_corners', 'away_corners', 'home_crosses',
       'away_crosses', 'home_interceptions', 'away_interceptions',
       'home_offsides', 'away_offsides', 'notes'],
      dtype='object')

In [19]:
data.duplicated().sum()

np.int64(0)

In [23]:
data['round'].unique()

array(['Group stage', 'Round of 32', 'Round of 16', 'Quarter-finals',
       'Semi-finals', 'Third-place match', 'Final'], dtype=object)

In [29]:
data['home_team'].nunique()

48