In [18]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns

The history saving thread hit an unexpected error (OperationalError('attempt to write a readonly database')).History will not be written to the database.

In [19]:
data = pd.read_csv("../analytics/matches_cleaned.csv")

In [20]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 104 entries, 0 to 103
Data columns (total 48 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   ROUND                  104 non-null    object
 1   DAYOFWEEK              104 non-null    object
 2   DATE                   104 non-null    object
 3   START_TIME             104 non-null    object
 4   HOME_TEAM              104 non-null    object
 5   AWAY_TEAM              104 non-null    object
 6   SCORE                  104 non-null    object
 7   HOME_SCORE             104 non-null    int64
 8   AWAY_SCORE             104 non-null    int64
 9   ATTENDANCE             104 non-null    int64
 10  VENUE                  104 non-null    object
 11  REFEREE                104 non-null    object
 12  HOME_FORMATION         104 non-null    object
 13  AWAY_FORMATION         104 non-null    object
 14  HOME_MANAGER           104 non-null    object
 15  AWAY_MANAGER           104 non-null    object
 16  HOME_CAPTAIN           104 non-null    object
 17  AWAY_CAPTAIN           104 non-null    object
 18  HOME_POSSESSION        104 non-null    int64
 19  AWAY_POSSESSION        104 non-null    int64
 20  HOME_SOT               104 non-null    int64
 21  AWAY_SOT               104 non-null    int64
 22  HOME_TOTAL_SHOTS       104 non-null    int64
 23  AWAY_TOTAL_SHOTS       104 non-null    int64
 24  HOME_SAVES             104 non-null    int64
 25  AWAY_SAVES             104 non-null    int64
 26  HOME_CARDS_YELLOW      104 non-null    int64
 27  AWAY_CARDS_YELLOW      104 non-null    int64
 28  HOME_CARDS_RED         104 non-null    int64
 29  AWAY_CARDS_RED         104 non-null    int64
 30  HOME_FOULS             104 non-null    int64
 31  AWAY_FOULS             104 non-null    int64
 32  HOME_CORNERS           104 non-null    int64
 33  AWAY_CORNERS           104 non-null    int64
 34  HOME_CROSSES           104 non-null    int64
 35  AWAY_CROSSES           104 non-null    int64
 36  HOME_INTERCEPTIONS     104 non-null    int64
 37  AWAY_INTERCEPTIONS     104 non-null    int64
 38  HOME_OFFSIDES          104 non-null    int64
 39  AWAY_OFFSIDES          104 non-null    int64
 40  TOTAL_GOALS            104 non-null    int64
 41  GOAL_DIFFERENCE        104 non-null    int64
 42  MATCH_RESULT           104 non-null    object
 43  TOTAL_YELLOW_CARDS     104 non-null    int64
 44  TOTAL_RED_CARDS        104 non-null    int64
 45  TOTAL_SHOTS_ON_TARGET  104 non-null    int64
 46  TOTAL_CORNERS          104 non-null    int64
 47  TOTAL_SAVES            104 non-null    int64
dtypes: int64(32), object(16)
memory usage: 39.1+ KB

In [21]:
data.shape

(104, 48)

In [22]:
data.describe()

,HOME_SCORE,AWAY_SCORE,ATTENDANCE,HOME_POSSESSION,AWAY_POSSESSION,HOME_SOT,AWAY_SOT,HOME_TOTAL_SHOTS,AWAY_TOTAL_SHOTS,HOME_SAVES,...,AWAY_INTERCEPTIONS,HOME_OFFSIDES,AWAY_OFFSIDES,TOTAL_GOALS,GOAL_DIFFERENCE,TOTAL_YELLOW_CARDS,TOTAL_RED_CARDS,TOTAL_SHOTS_ON_TARGET,TOTAL_CORNERS,TOTAL_SAVES
count,104.000000,104.000000,104.000000,104.000000,104.000000,104.000000,104.000000,104.000000,104.000000,104.000000,...,104.000000,104.000000,104.000000,104.000000,104.000000,104.000000,104.000000,104.000000,104.000000,104.000000
mean,1.692308,1.211538,65490.057692,52.423077,47.701923,4.846154,3.673077,14.019231,10.769231,2.403846,...,8.634615,1.826923,1.711538,2.903846,1.557692,2.663462,0.144231,8.519231,9.144231,5.528846
std,1.526955,1.251586,10052.949890,13.101317,13.093302,3.108926,2.502202,6.422020,5.846301,1.913261,...,3.128503,1.541921,1.605047,1.923383,1.371180,1.776932,0.449774,3.404682,3.545593,2.892765
min,0.000000,0.000000,42942.000000,24.000000,21.000000,0.000000,0.000000,2.000000,2.000000,0.000000,...,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,2.000000,1.000000
25%,0.750000,0.000000,63998.000000,43.000000,38.000000,2.000000,2.000000,8.750000,7.000000,1.000000,...,6.000000,1.000000,0.000000,1.750000,1.000000,1.000000,0.000000,6.000000,7.000000,3.000000
50%,1.000000,1.000000,68276.000000,52.500000,47.500000,4.000000,3.000000,13.000000,10.000000,2.000000,...,8.500000,2.000000,1.000000,3.000000,1.000000,2.000000,0.000000,8.000000,9.000000,5.000000
75%,3.000000,2.000000,70046.500000,62.000000,57.000000,7.000000,5.000000,19.000000,14.000000,3.000000,...,11.000000,3.000000,3.000000,4.000000,2.000000,4.000000,0.000000,10.000000,11.000000,7.000000
max,7.000000,6.000000,80824.000000,79.000000,76.000000,15.000000,11.000000,32.000000,35.000000,9.000000,...,16.000000,8.000000,6.000000,10.000000,6.000000,8.000000,3.000000,20.000000,22.000000,18.000000

In [23]:
data.columns

Index(['ROUND', 'DAYOFWEEK', 'DATE', 'START_TIME', 'HOME_TEAM', 'AWAY_TEAM',
       'SCORE', 'HOME_SCORE', 'AWAY_SCORE', 'ATTENDANCE', 'VENUE', 'REFEREE',
       'HOME_FORMATION', 'AWAY_FORMATION', 'HOME_MANAGER', 'AWAY_MANAGER',
       'HOME_CAPTAIN', 'AWAY_CAPTAIN', 'HOME_POSSESSION', 'AWAY_POSSESSION',
       'HOME_SOT', 'AWAY_SOT', 'HOME_TOTAL_SHOTS', 'AWAY_TOTAL_SHOTS',
       'HOME_SAVES', 'AWAY_SAVES', 'HOME_CARDS_YELLOW', 'AWAY_CARDS_YELLOW',
       'HOME_CARDS_RED', 'AWAY_CARDS_RED', 'HOME_FOULS', 'AWAY_FOULS',
       'HOME_CORNERS', 'AWAY_CORNERS', 'HOME_CROSSES', 'AWAY_CROSSES',
       'HOME_INTERCEPTIONS', 'AWAY_INTERCEPTIONS', 'HOME_OFFSIDES',
       'AWAY_OFFSIDES', 'TOTAL_GOALS', 'GOAL_DIFFERENCE', 'MATCH_RESULT',
       'TOTAL_YELLOW_CARDS', 'TOTAL_RED_CARDS', 'TOTAL_SHOTS_ON_TARGET',
       'TOTAL_CORNERS', 'TOTAL_SAVES'],
      dtype='object')

In [24]:
data.head(5)

,ROUND,DAYOFWEEK,DATE,START_TIME,HOME_TEAM,AWAY_TEAM,SCORE,HOME_SCORE,AWAY_SCORE,ATTENDANCE,...,HOME_OFFSIDES,AWAY_OFFSIDES,TOTAL_GOALS,GOAL_DIFFERENCE,MATCH_RESULT,TOTAL_YELLOW_CARDS,TOTAL_RED_CARDS,TOTAL_SHOTS_ON_TARGET,TOTAL_CORNERS,TOTAL_SAVES
0,Group stage,Thu,2026-06-11,13:00,Mexico,South Africa,2–0,2,0,80824,...,1,1,2,2,Home Win,3,3,6,4,4
1,Group stage,Thu,2026-06-11,20:00,Korea Republic,Czechia,2–1,2,1,44985,...,2,2,3,1,Home Win,1,0,10,9,7
2,Group stage,Fri,2026-06-12,15:00,Canada,Bosnia–Herz,1–1,1,1,43002,...,1,0,2,0,Draw,5,0,7,13,3
3,Group stage,Fri,2026-06-12,18:00,United States,Paraguay,4–1,4,1,70492,...,2,1,5,3,Home Win,6,0,7,4,3
4,Group stage,Sat,2026-06-13,12:00,Qatar,Switzerland,1–1,1,1,67966,...,0,1,2,0,Draw,3,0,11,13,8

In [25]:
# FIFA World Cup 2026 - Final Insights 

print("Total Matches :", len(data))
print("Total Teams :", len(set(data["HOME_TEAM"]).union(set(data["AWAY_TEAM"]))))
print("Tournament Rounds :", data["ROUND"].nunique())
print("Host Venues :", data["VENUE"].nunique())

Total Matches : 104
Total Teams : 48
Tournament Rounds : 7
Host Venues : 17

In [26]:
print("Average Goals per Match :", round(data["TOTAL_GOALS"].mean(),2))
print("Highest Goals in a Match :", data["TOTAL_GOALS"].max())
print("Total Goals :", data["TOTAL_GOALS"].sum())

Average Goals per Match : 2.9
Highest Goals in a Match : 10
Total Goals : 302

In [27]:
print("Average Attendance :", round(data["ATTENDANCE"].mean(),2))
print("Highest Attendance :", data["ATTENDANCE"].max())
print("Lowest Attendance :", data["ATTENDANCE"].min())

Average Attendance : 65490.06
Highest Attendance : 80824
Lowest Attendance : 42942

In [28]:
print("Average Home Possession :", round(data["HOME_POSSESSION"].mean(),2))
print("Average Away Possession :", round(data["AWAY_POSSESSION"].mean(),2))

Average Home Possession : 52.42
Average Away Possession : 47.7

In [29]:
print("Average Home Shots :", round(data["HOME_TOTAL_SHOTS"].mean(),2))
print("Average Away Shots :", round(data["AWAY_TOTAL_SHOTS"].mean(),2))

print("Average Home Shots on Target :", round(data["HOME_SOT"].mean(),2))
print("Average Away Shots on Target :", round(data["AWAY_SOT"].mean(),2))

Average Home Shots : 14.02
Average Away Shots : 10.77
Average Home Shots on Target : 4.85
Average Away Shots on Target : 3.67

In [30]:
print("Average Home Fouls :", round(data["HOME_FOULS"].mean(),2))
print("Average Away Fouls :", round(data["AWAY_FOULS"].mean(),2))

print("Average Home Yellow Cards :", round(data["HOME_CARDS_YELLOW"].mean(),2))
print("Average Away Yellow Cards :", round(data["AWAY_CARDS_YELLOW"].mean(),2))

Average Home Fouls : 11.62
Average Away Fouls : 11.57
Average Home Yellow Cards : 1.15
Average Away Yellow Cards : 1.51

In [32]:
correlation_matrix = pd.read_csv(

    "../analytics/correlation_matrix.csv",

    index_col=0

)

correlation_matrix

,HOME_SCORE,AWAY_SCORE,TOTAL_GOALS,ATTENDANCE,HOME_POSSESSION,AWAY_POSSESSION,HOME_SOT,AWAY_SOT,HOME_TOTAL_SHOTS,AWAY_TOTAL_SHOTS
HOME_SCORE,1.000000,-0.051974,0.760070,0.031829,0.333186,-0.332904,0.599388,-0.156177,0.362974,-0.194005
AWAY_SCORE,-0.051974,1.000000,0.609460,0.096088,-0.276096,0.275228,-0.211126,0.623722,-0.263833,0.460518
TOTAL_GOALS,0.760070,0.609460,1.000000,0.087795,0.084852,-0.085193,0.338464,0.281882,0.116480,0.145650
ATTENDANCE,0.031829,0.096088,0.087795,1.000000,0.051027,-0.051170,0.073737,-0.031852,0.104461,-0.065604
HOME_POSSESSION,0.333186,-0.276096,0.084852,0.051027,1.000000,-0.999678,0.546748,-0.458637,0.681639,-0.536029
AWAY_POSSESSION,-0.332904,0.275228,-0.085193,-0.051170,-0.999678,1.000000,-0.546367,0.458399,-0.678737,0.536357
HOME_SOT,0.599388,-0.211126,0.338464,0.073737,0.546748,-0.546367,1.000000,-0.278602,0.739772,-0.289884
AWAY_SOT,-0.156177,0.623722,0.281882,-0.031852,-0.458637,0.458399,-0.278602,1.000000,-0.386886,0.807802
HOME_TOTAL_SHOTS,0.362974,-0.263833,0.116480,0.104461,0.681639,-0.678737,0.739772,-0.386886,1.000000,-0.397590
AWAY_TOTAL_SHOTS,-0.194005,0.460518,0.145650,-0.065604,-0.536029,0.536357,-0.289884,0.807802,-0.397590,1.000000

In [34]:
## Conclusion

##The FIFA World Cup 2026 dataset provides valuable insights into team performance, match statistics, scoring trends, and tournament dynamics.

##Through data cleaning, exploratory data analysis, and statistical analysis, meaningful patterns were identified that help explain offensive performance, defensive discipline, possession trends, attendance, and overall tournament characteristics.

##The cleaned dataset and analytical findings developed in this project will be utilized to build an interactive MERN-based analytics dashboard, enabling users to explore FIFA World Cup 2026 statistics through dynamic visualizations and REST APIs.